---
title: "Social Behaviour"
format: docx
editor: visual
---

```{r}
#| echo: false
#| warning: false
#| include: false

library(tidyverse)
library(ggplot2)
library(patchwork)
```

# Distances between individuals

```{r}
#| fig-cap: "Figure S?|."
#| echo: false
#| label: socDist
#| message: false

ddist<-readRDS( "../../data/DFs/socialDist.rds")%>%
  mutate(MONTH = substr(DTIME, 6,7),
         YEAR = substr(DTIME, 1,4))
 
# group_by(BandNumber2)%>%
 # summarise(mean(dist))

# No trend in overlap on yearly cycle
ggplot(ddist, aes(x=MONTH, y=dist))+
  geom_boxplot()+
  facet_wrap(~YEAR, ncol = 2)+
  theme_classic()+
  labs(x="Month", y="Distance (m)")


```

# Site fidelity

```{r}
#| echo: false
#| message: false
#| warning: false
#| label: fidelity
#| fig-height: 7
#| fig-width: 7
#| fig-cap: Figure S?| A. Foraging site fidelity as overlap of monthly 95% KDE per individual. B. Foraging site fidelity as overlap of monthly 95% KDE across all individuals

# A4 dim: 8.3 x 11.7

siteFidelity<-readRDS( "../../data/monthlySiteFidelity.RDS")


## matching months of the year ====
sm<-do.call('rbind', siteFidelity)%>%
  mutate(M1=substr(YM.x, 5, nchar(YM.x)),
         M2=substr(YM.y, 5, nchar(YM.y)),
         Y=substr(YM.y, 1, 4))%>%
  filter(M1==M2)%>%
  arrange(M1)%>%
  mutate(
    SEASON = case_when(
      M1 %in% c(12, 1, 2) ~ "Summer",
      M1 %in%  3:5  ~ "Autumn",
      M1 %in%  6:8  ~ "Winter",
      M1 %in%  9:11  ~ "Spring"),
    WS = case_when(
      M1 %in% c(10,11, 12, 1, 2, 3) ~ "Summer",
      M1 %in%  c(4,5,6,7,8,9)  ~ "Winter"
    ))

## At individual levels ====
p1<-ggplot(sm, aes(x=as.numeric(M1), y=overlap))+
  geom_point()+
  geom_smooth(se = F)+
  facet_wrap(~BandNumber)+
  theme_classic()+
  scale_x_continuous(breaks = 1:12)+
  labs(x="Month")

p2<-ggplot(sm, aes(x=as.numeric(M1), y=overlap))+
  geom_smooth()+
    geom_point()+
  theme_classic()+
  scale_x_continuous(breaks = 1:12)+
  labs(x="Month")



fplot<-(p1)/(p2) + plot_annotation(tag_levels = 'A')


fplot
```

# Territoriality

```{r}
#| echo: false
#| message: false
#| warning: false
#| label: terri
#| fig-height: 7
#| fig-width: 7
#| fig-cap: Figure S?| A. Foraging site territory as overlap of monthly 95% KDE per individual. B. Foraging site fidelity as overlap of monthly 95% KDE across all individuals

dfterry<-readRDS( "../../data/DFs/dfterries.rds")

## Plot territory overlaps ===============
p1<-ggplot(dfterry, aes(x=DATE, y=overlap, group=BandNumber.y, col=BandNumber.y))+
  geom_point()+
  geom_line() +
  facet_wrap(~BandNumber.x)+
  labs(x="Date", y="Percentage overlap", col="Individual ID")+
  theme_classic()

p2<-ggplot()+
  geom_point(data=dfterry, aes(x=DATE, y=overlap))+
  geom_smooth(data=dfterry, aes(x=DATE, y=overlap), method = 'gam') +
  #facet_wrap(~BandNumber.x)+
  labs(x="Date", y="Percentage overlap")+
  theme_classic()





fplot<-(p1)/(p2) + plot_annotation(tag_levels = 'A') +   plot_layout(heights = c(5, 2))


fplot

```
